import 'package:get/get_navigation/src/root/internacionalization.dart';
import '../utils/constants.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      wel_1:'Create Your Budget',
      wel_2: 'Increase your savings in every month and see the analytics also to view',
      wel_btn:'Get Started',
      sign_1:'Sign in',
      sign_rem:'Remember Me',
      sign_don:'Don\'t have an account?',
      sign_up:'Sign up',
      e_hint:'Enter Your Email',
      p_hint:'Your Password',
      e_r_p:'email or password not valid',
      n_hint:'Full Name',
      c_hint:'Confirm Password',
      sign_al:'Already have an account?',
      dob_si:'Date of Birth',
      acc_bal:'Account Balance',
      inc_bal:'Income',
      exp_bal:'Expenses',
      all_bi:'All',
      food_bi:'Food',
      trans_bi:'Transportation',
      subs_bi:'Subscription',
      bill_bi:'Bills',
      shop_bi:'Shopping',
      ente_bi:'Entertainment',
      othe_bi:'Others',
      home_bi:'Home',
      anal_bi:'Analytics',
      prof_bi:'Profile',
      add_bi:'Add Expenses',
      fil_bi:'Filter By',
      tr_bi:'Transfer',
      so_bi:'Sort By',
      hi_bi:'Highest',
      low_bi:'Lowest',
      ex_am_bi:'Expense Amount',
      en_am_hint:'Enter Your Amount',
      not_bi:'Notes',
      not_hint:'Enter Your Notes',
      ch_ca_bi:'Choose Category',
      sel_ca_bi:'Select Category',
      sub_btn:'Submit',
      jan_:'january',
      feb_:'february',
      mar_:'march',
      apr_:'april',
      may_:'may',
      jun_:'june',
      jul_:'july',
      aug_:'august',
      sep_:'september',
      oct_:'october',
      nov_:'november',
      dec_:'december',
      user_bi:'user name',
      acc_bi:'account',
      set_bi:'settings',
      up_in_bi:'Update Income',
      log_bi:'LogOut',
      ch_n_bi:'Change your Name',
      can_bi:'Cancel',
      up_bi:'Update',
      pl_in_bi:'Please enter your Income',
      ar_lo_bi:'Are you sure want to LogOut?',
      lod_bi:'Loading...',
      slog:'of your Income spends Expenses',
      dl_ac:'Delete Account',
      sec_bi:'Security',
      lang_bi:'Language',
      ch_pa_bi:'Change Password',
      ab_se:'About',
      new_bo:'New Password',
    },
    'ta_LK': {
      wel_1: 'உங்கள் பட்ஜெட்டை உருவாக்கவும்',
      wel_2: 'ஒவ்வொரு மாதமும் உங்கள் சேமிப்பை அதிகரித்து, பார்க்க வேண்டிய பகுப்பாய்வுகளையும் பாருங்கள்',
      wel_btn: 'தொடங்குங்கள்',
      sign_1:'உள்நுழைக',
      sign_rem:'என்னை ஞாபகம் வைத்துக் கொள்',
      sign_don:'கணக்கு இல்லையா?',
      sign_up:'பதிவுபெறு',
      e_hint:'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      p_hint:'உங்கள் கடவுச்சொல்',
      e_r_p:'மின்னஞ்சல் அல்லது கடவுச்சொல் செல்லுபடியாகாது',
      n_hint:'முழுப் பெயர்',
      c_hint:'கடவுச்சொல்லை உறுதிப்படுத்துக',
      sign_al:'ஏற்கனவே ஒரு கணக்கு உள்ளது?',
      dob_si:'பிறந்த நாள்',
      acc_bal:'கணக்கு இருப்பு',
      inc_bal:'வருமானம்',
      exp_bal:'செலவுகள்',
      all_bi:'அனைத்தும்',
      food_bi:'உணவு',
      trans_bi:'போக்குவரத்து',
      subs_bi:'சந்தா',
      bill_bi:'பில்கள்',
      shop_bi:'ஷாப்பிங்',
      ente_bi:'பொழுதுபோக்கு',
      othe_bi:'மற்றது',
      home_bi:'இல்லம்',
      anal_bi:'பகுப்பாய்வு',
      prof_bi:'சுயவிவரம்',
      add_bi:'செலவுகளைச் சேர்க்கவும்',
      fil_bi:'வடிகட்டி',
      tr_bi:'இடமாற்றம்',
      so_bi:'வரிசைப்படுத்து',
      hi_bi:'உயர்ந்தது',
      low_bi:'லோவெஸ்ட்',
      ex_am_bi:'செலவு தொகை',
      en_am_hint:'உங்கள் தொகை',
      not_bi:'குறிப்புகள்',
      not_hint:'உங்கள் குறிப்புகள்',
      ch_ca_bi:'வகை தேர்வு',
      sel_ca_bi:'தேர்வு செய்யவும்',
      sub_btn:'சமர்ப்பி',
      jan_:'ஜனவரி',
      feb_:'பிப்ரவரி',
      mar_:'மார்ச்',
      apr_:'ஏப்ரல்',
      may_:'கூடும்',
      jun_:'ஜூன்',
      jul_ :'ஜூலை',
      aug_:'ஆகஸ்ட்',
      sep_:'செப்டம்பர்',
      oct_:'அக்டோபர்',
      nov_:'நவம்பர்',
      dec_:'டிசம்பர்',
      user_bi:'பயனர் பெயர்',
      acc_bi:'கணக்கு',
      set_bi:'அமைப்புகள்',
      up_in_bi:'வருமானத்தைப் புதுப்பிக்கவும்',
      log_bi:'வெளியேறு',
      ch_n_bi:'உங்கள் பெயரை மாற்றவும்',
      can_bi:'ரத்துசெய்',
      up_bi:'அப்டேட்',
      pl_in_bi:'உங்கள் வருமானத்தை உள்ளிடவும்',
      ar_lo_bi:'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      lod_bi:'ஏற்றுதல்...',
      slog:'உங்கள் வருமானம் செலவுகள்',
      dl_ac:'கணக்கை நீக்கு',
      sec_bi:'பாதுகாப்பு',
      lang_bi:'மொழி',
      ch_pa_bi:'கடவுச்சொல் மாற்ற',
      ab_se:'பற்றி',
      new_bo:'புதிய கடவுச்சொல்',
    }
  };
}